export { default as ObjectivesSection } from './ObjectivesSection'
export { default as TradingPerformanceSection } from './TradingPerformanceSection'
export { default as EquityCurveSection } from './EquityCurveSection'
export { default as TradeDataSection } from './TradeDataSection'
export { default as DailyAnalysisSection } from './DailyAnalysisSection'
export { default as AnalyticsOverviewSection } from './AnalyticsOverviewSection' 